name: Build VEGA
concurrency: ${{ github.workflow }}_${{ github.ref }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project
      run: ./build.cmd
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: vega-windows
        path: bin
    - name: Compress the binary for releases
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'vega-windows.zip'
        path: bin/
    - name: Upload to Release Action
      uses: softprops/action-gh-release@v2
      with:
        body: automatic release by github actions
        prerelease: true
        files: ${{ github.workspace }}/vega-windows.zip
        name: autobuild
        tag_name: autobuild
        make_latest: true
    - name: Discord WebHook Notify
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        username: "VEGAbot"
        avatar-url: "https://maksw.pl/images/ja1.webp"
        embed-title: "A new release dropped!"
        embed-description: "[Get it here](https://github.com/maksw2/VEGA/releases)"
        embed-color: 5814783
