name: build vega

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  #build-linux:
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v4
    #- name: perms fix
    #  run: chmod +x build_only.sh
    #- name: make
    #  run: ./build_only.sh
    #- uses: actions/upload-artifact@v4.3.3
    #  with:
    #    name: vega-linux
    #    path: bin
    #- name: Upload to Release Action
    #  uses: Shopify/upload-to-release@v2.0.0
    #  with:
    #      name: vega-linux
    #      path: bin
    #      repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: ./build_only.cmd
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: vega-windows
        path: bin
    - name: compress bin
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'vega-windows.zip'
        path: bin/
    - name: Upload to Release Action
      uses: softprops/action-gh-release@v2
      with:
        body: automatic release by github actions
        prerelease: true
        files: ${{ github.workspace }}/vega-windows.zip
        name: autobuild
        tag_name: autobuild
    - name: notify discord
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        username: "vegabot"
        avatar-url: "https://maksw.pl/images/ja1.webp"
        embed-title: "A new release dropped!"
        embed-description: "[Get it here](https://github.com/maksw2/VEGA/releases)"
        embed-color: 5814783
