name: build vega

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: perms fix
      run: chmod +x build_norun.sh
    - name: make
      run: ./build_norun.sh
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: vega-linux
        path: bin
    - name: Upload to Release Action
      uses: Shopify/upload-to-release@v2.0.0
      with:
          name: vega-linux
          path: bin
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: ./build_norun.cmd
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: vega-windows
        path: bin
    - name: Upload to Release Action
      uses: softprops/action-gh-release@v2
      with:
          body: automatic release by github actions
          prerelease: true
          files: ${{ github.workspace }}/bin/*.zip
          name: autobuild
          tag_name: autobuild
